name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # run daily
  workflow_dispatch:       # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 allow this job to push generated files
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Rohan12190
